# Generated by Django 5.0.1 on 2024-01-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
