# Generated by Django 5.0.1 on 2024-02-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_comment_listing_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='endAmont',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
