# Generated by Django 5.0.1 on 2024-02-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('comment', models.TextField()),
                ('auction_listings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='auctions.auction_listings')),
            ],
        ),
    ]
