# Generated by Django 5.0.1 on 2024-02-01 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
