# Generated by Django 5.0.1 on 2024-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_endamont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='endAmont',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
