# Generated by Django 5.0.1 on 2024-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_endamont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='amount',
            field=models.IntegerField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='endAmont',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='paid',
            name='Paid_amount',
            field=models.IntegerField(max_length=64),
        ),
    ]
