# Generated by Django 5.0.1 on 2024-02-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listings_status_auction_listings_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='Paid_amount',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
